### ISSUE TITLE
钉钉推送失败

### ISSUE THREAD

**Issue by ffutop** [AliyunContainerService/kube-eventer#17]
## 配置信息

```
image: registry.cn-beijing.aliyuncs.com/acs/kube-eventer-amd64:v1.0.0-d9898e1-aliyun
name: kube-eventer
command
  - "/kube-eventer"
  - "--source=kubernetes:https://kubernetes.default"
  - "--sink=dingtalk:https://oapi.dingtalk.com/robot/send?access_token=<My-Token>&label=Kubernetes-Test&level=Normal"
```

## 日志信息

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xad615f]

goroutine 28 [running]:
github.com/AliyunContainerService/kube-eventer/sinks/dingtalk.(*DingTalkSink).Ding(0xc00030c380, 0xc000144780)
	/src/github.com/AliyunContainerService/kube-eventer/sinks/dingtalk/dingtalk.go:151 +0x30f
github.com/AliyunContainerService/kube-eventer/sinks/dingtalk.(*DingTalkSink).ExportEvents(0xc00030c380, 0xc000102720)
	/src/github.com/AliyunContainerService/kube-eventer/sinks/dingtalk/dingtalk.go:93 +0x97
github.com/AliyunContainerService/kube-eventer/sinks.export(0x17ea640, 0xc00030c380, 0xc000102720)
	/src/github.com/AliyunContainerService/kube-eventer/sinks/manager.go:145 +0x91
github.com/AliyunContainerService/kube-eventer/sinks.NewEventSinkManager.func1(0x17ea640, 0xc00030c380, 0xc00012f320, 0xc00012f380)
	/src/github.com/AliyunContainerService/kube-eventer/sinks/manager.go:77 +0x216
created by github.com/AliyunContainerService/kube-eventer/sinks.NewEventSinkManager
	/src/github.com/AliyunContainerService/kube-eventer/sinks/manager.go:73 +0x199
```

**Comment by ringtail** [comment]
#13
